/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DayOfWeek = IDL.Nat;
export const RoutineId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Routine = IDL.Record({
  'id' : RoutineId,
  'repeatDays' : IDL.Vec(DayOfWeek),
  'scheduledTime' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyRoutineStatus = IDL.Record({
  'status' : IDL.Opt(IDL.Text),
  'routine' : Routine,
});
export const LogId = IDL.Nat;
export const RoutineLog = IDL.Record({
  'id' : LogId,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'routineId' : RoutineId,
  'loggedAt' : Timestamp,
});
export const RoutineUpdate = IDL.Record({
  'repeatDays' : IDL.Opt(IDL.Vec(DayOfWeek)),
  'scheduledTime' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoutine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(DayOfWeek)],
      [RoutineId],
      [],
    ),
  'deleteRoutine' : IDL.Func([RoutineId], [], []),
  'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyRoutinesWithStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyRoutineStatus)],
      ['query'],
    ),
  'getRoutine' : IDL.Func([RoutineId], [IDL.Opt(Routine)], ['query']),
  'getRoutineLogs' : IDL.Func([RoutineId], [IDL.Vec(RoutineLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logRoutine' : IDL.Func([RoutineId, IDL.Text, IDL.Text], [LogId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRoutine' : IDL.Func([RoutineId, RoutineUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DayOfWeek = IDL.Nat;
  const RoutineId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Routine = IDL.Record({
    'id' : RoutineId,
    'repeatDays' : IDL.Vec(DayOfWeek),
    'scheduledTime' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyRoutineStatus = IDL.Record({
    'status' : IDL.Opt(IDL.Text),
    'routine' : Routine,
  });
  const LogId = IDL.Nat;
  const RoutineLog = IDL.Record({
    'id' : LogId,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'routineId' : RoutineId,
    'loggedAt' : Timestamp,
  });
  const RoutineUpdate = IDL.Record({
    'repeatDays' : IDL.Opt(IDL.Vec(DayOfWeek)),
    'scheduledTime' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoutine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(DayOfWeek)],
        [RoutineId],
        [],
      ),
    'deleteRoutine' : IDL.Func([RoutineId], [], []),
    'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyRoutinesWithStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyRoutineStatus)],
        ['query'],
      ),
    'getRoutine' : IDL.Func([RoutineId], [IDL.Opt(Routine)], ['query']),
    'getRoutineLogs' : IDL.Func([RoutineId], [IDL.Vec(RoutineLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logRoutine' : IDL.Func([RoutineId, IDL.Text, IDL.Text], [LogId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRoutine' : IDL.Func([RoutineId, RoutineUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };